___

<a href='https://oxiane-institut.com/'> <img src='../oxiane.jpg' /></a>
___

# San Francisco Salaries Exercise

Welcome to a quick exercise to practice your pandas skills! 

We will be using the [San Francisco Salaries dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! 

Simply follow along and complete the tasks described in bold below. 

The tasks will become increasingly challenging as you progress.

**Import pandas as pd.**

In [21]:
import pandas as pd

**Read Salaries.csv as a DataFrame and name it sal.**

In [22]:
sal = pd.read_csv('Salaries.csv')
sal

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

**Check the header of the DataFrame.**

In [23]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**Use the .info() method to find out how many entries are present.**

In [24]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**What is the average of BasePay?**

In [25]:
sal["BasePay"].mean()

66325.4488404877

**What is the highest value of OvertimePay in the dataset?**

In [26]:
sal["OvertimePay"].max()

245131.88

What is JOSEPH DRISCOLL's job title? 

Note: Use uppercase, otherwise you might get a mismatched answer (there is also a lowercase Joseph Driscoll).

In [27]:
sal.loc[sal["EmployeeName"] == "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

**How much does JOSEPH DRISCOLL earn (including benefits)?**

In [28]:
sal.loc[~(sal["TotalPayBenefits"] == (sal["TotalPay"] + sal["Benefits"]))]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148604,148605,Sugyn M Paynay,Publ Svc Aide-Asst to Prof,34.03,0.00,0.00,0.34,34.03,34.37,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN

In [29]:
sal.loc[sal["EmployeeName"] == "JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

**What is the name of the highest paid person (including benefits)?**

In [30]:
sal.loc[sal["TotalPayBenefits"].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

**What is the name of the lowest paid person (including benefits)? Do you notice anything strange about their salary amount?**

In [31]:
sal.loc[sal["TotalPayBenefits"].argsort()].head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,NaN
110530,110531,David P Kucia,Police Officer 3,NaN,0.0,0.00,-33.89,0.00,-33.89,2013,NaN,San Francisco,NaN
110529,110530,Mark E Laherty,Police Officer 3,NaN,0.0,0.00,-8.20,0.00,-8.20,2013,NaN,San Francisco,NaN
110528,110529,Timothy E Gibson,Police Officer 3,NaN,0.0,0.00,-2.73,0.00,-2.73,2013,NaN,San Francisco,NaN
148633,148634,Edward Ferdinand,General Laborer,0.0,0.0,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,NaN

**What was the average (mean) base salary of all employees per year? (2011-2014)?**

In [32]:
sal.groupby("Year").mean(numeric_only=True)["BasePay"]

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

**How many unique job titles are there?**

In [33]:
sal["JobTitle"].nunique()

2159

**What are the 5 most common jobs?**

In [34]:
sal["JobTitle"].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

**How many job titles were represented by a single person in 2013? (i.e., job titles with only one occurrence in 2013?)**

In [35]:
sal_2013 = sal.loc[sal["Year"] == 2013]
sal_2013

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.00,20007.06,86533.21,339282.07,425815.28,2013,NaN,San Francisco,NaN
72926,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.00,23236.00,85431.39,336922.01,422353.40,2013,NaN,San Francisco,NaN
72927,72928,Samson Lai,"Battalion Chief, Fire Suppress",186236.42,131217.63,29648.27,57064.95,347102.32,404167.27,2013,NaN,San Francisco,NaN
72928,72929,Ellen G Moffatt,Asst Med Examiner,272855.51,23727.91,38954.54,66198.92,335537.96,401736.88,2013,NaN,San Francisco,NaN
72929,72930,Robert L Shaw,"Dep Dir for Investments, Ret",315572.01,0.00,0.00,82849.66,315572.01,398421.67,2013,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110526,110527,Arthur L Curry,PS Aide Health Services,NaN,0.00,10.67,0.00,10.67,10.67,2013,NaN,San Francisco,NaN
110527,110528,Nereida Vega,Senior Clerk,NaN,0.00,5.56,0.00,5.56,5.56,2013,NaN,San Francisco,NaN
110528,110529,Timothy E Gibson,Police Officer 3,NaN,0.00,0.00,-2.73,0.00,-2.73,2013,NaN,San Francisco,NaN
110529,110530,Mark E Laherty,Police Officer 3,NaN,0.00,0.00,-8.20,0.00,-8.20,2013,NaN,San Francisco,NaN
110530,110531,David P Kucia,Police Officer 3,NaN,0.00,0.00,-33.89,0.00,-33.89,2013,NaN,San Francisco,NaN

In [36]:
all_titles_count = sal_2013["JobTitle"].value_counts()
all_titles_count

JobTitle
Transit Operator                  2295
Special Nurse                     1445
Registered Nurse                  1231
Public Svc Aide-Public Works       859
Custodian                          789
                                  ...
Sr General Utility Mechanic          1
Sprv Adult Prob Ofc (SFERS)          1
Mayoral Staff XII                    1
Pr Investigator, Tax Collector       1
Senior Assessment Clerk              1
Name: count, Length: 1051, dtype: int64

In [37]:
all_titles_count.value_counts()

count
1      202
2       69
3       65
4       58
5       51
      ...
158      1
168      1
175      1
177      1
85       1
Name: count, Length: 152, dtype: int64

In [38]:
series_of_unique_titles = all_titles_count == 1
series_of_unique_titles

JobTitle
Transit Operator                  False
Special Nurse                     False
Registered Nurse                  False
Public Svc Aide-Public Works      False
Custodian                         False
                                  ...
Sr General Utility Mechanic        True
Sprv Adult Prob Ofc (SFERS)        True
Mayoral Staff XII                  True
Pr Investigator, Tax Collector     True
Senior Assessment Clerk            True
Name: count, Length: 1051, dtype: bool

In [39]:
series_of_unique_titles.sum()

202

In [41]:
sal_2013 = sal.loc[sal["Year"] == 2013]

list_of_all_job_titles = sal_2013["JobTitle"].unique().tolist()

list_of_all_job_titles

['Chief of Police',
 'Chief, Fire Department',
 'Battalion Chief, Fire Suppress',
 'Asst Med Examiner',
 'Dep Dir for Investments, Ret',
 'Asst Chf of Dept (Fire Dept)',
 'Executive Contract Employee',
 'Dept Head V',
 'Gen Mgr, Public Trnsp Dept',
 'Senior Physician Specialist',
 'Deputy Chief 3',
 'Dep Chf of Dept (Fire Dept)',
 'Lieutenant, Fire Suppression',
 'Mayor',
 'Assistant Deputy Chief 2',
 'Adm, SFGH Medical Center',
 'Captain, Fire Suppression',
 'Controller',
 'Deputy Sheriff',
 'Anesthetist',
 'EMT/Paramedic/Firefighter',
 'Inspector 3',
 'Port Director',
 'Emergency Medical Svcs Chief',
 'Dep Dir V',
 'Lieutenant 3',
 'Deputy Dir II, MTA',
 'Commander 3',
 'Incident Support Specialist',
 'Nursing Supervisor',
 'District Attorney',
 'Captain, Emergency Med Svcs',
 'Firefighter',
 'Manager VIII',
 'City Attorney',
 'Dept Head IV',
 'Lieut,Fire Prev',
 'Police Officer 2',
 'Police Officer',
 'Sheriff (SFERS)',
 'Administrator, DPH',
 'Nurse Manager',
 'Sergeant 3',
 'Captain 3',
 'Supervising Physician Spec',
 'Nursing Supervisor Psychiatric',
 'Capt,Fire Prev or Fire Invsgtn',
 'Public Defender',
 'Cfdntal Chf Atty 2,(Cvl&Crmnl)',
 'Marine Engineer of Fire Boats',
 'Forensic Toxicologist',
 'Assistant Inspector 3',
 'Dep Dir IV',
 'Court Executive Officer',
 'Special Assistant 22',
 'Chief Atty1 (Civil & Criminal)',
 'Nurse Practitioner',
 'Police Officer 3',
 'Attorney (Civil/Criminal)',
 'Human Resources Director',
 'Dir Emp Relations Div',
 'Assistant Chief Attorney 2',
 'Chief Adult Probation Officer',
 'Transit Supervisor',
 'Manager VIII, MTA',
 'Deputy Dir I, MTA',
 'Physician Specialist',
 'Special Assistant 21',
 'Dept Head III',
 'Undersheriff',
 'Physician Assistant',
 'Project Manager 4',
 'Manager VII',
 'Insp, Fire Dept',
 'Fire Safety Inspector 2',
 "Sheriff's Lieutenant",
 'Assistant Chief Attorney 1',
 "Sheriff's Sergeant",
 'Manager VI',
 'Pilot of Fire Boats',
 'Track Maint Wrk Sprv 1',
 'Electrical Transit Shop Sprv 1',
 'Engineer/Architect Principal',
 'Head Atty, Civil & Criminal',
 'Diagnostic Imaging Tech III',
 'Dep Dir III',
 'Sergeant 2',
 'Dept Head II',
 'Dept Head I',
 'Clinical Nurse Specialist',
 'Assistant Sheriff',
 'Diagnostic Imaging Tech II',
 'Mayoral Staff XVII',
 'Engineer',
 'Eng/Arch/Landscape Arch Sr',
 'Pharmacist',
 'Landscape Architect Assoc 2',
 'Registered Nurse',
 'Director, Info Tech Group',
 'Manager VII, MTA',
 'Manager V',
 'Senior Deputy Sheriff',
 'Heating/Ventilating Inspector',
 'Chief Deputy Sheriff',
 'Assistant Inspector',
 'Manager IV',
 'Invstgtor,Fire Dept',
 'IS Manager',
 'Power Generation Supervisor',
 'Electrl Trnst Mech, Asst Sprv',
 'Special Assistant 19',
 'Treasurer',
 "Sheriff's Captain",
 'Electr Maint Tech Asst Sprv',
 'Board Scty, MTA',
 'Lieutenant 2',
 'Electronic Maintenance Tech',
 'Sergeant, (Police Department)',
 'Senior Comm Systems Technican',
 'Chf Prob Ofc, Juv Court',
 'Wire Rope Cable Maint Sprv',
 'Project Manager 3',
 'Train Controller',
 'Manager VI, MTA',
 'Transmission Line Supervisor 1',
 'Managing Attorney',
 'Court Commissioner',
 'Water Const&Main Supt',
 'Inspector, (Police Department)',
 'IS Engineer-Principal',
 'Assessor',
 'Supervising Pharmacist',
 'Bldgs & Grounds Maint Supt',
 'Chf District Atty Investigator',
 'Communications Systems Tech',
 'Architectural Associate 1',
 'Law Librarian',
 'Assoc Engineer',
 'Electrical Transit System Mech',
 'Clinical Pharmacist',
 'Chief Dep Adlt Prob Of (SFERS)',
 'Trnst Power Line Wrk Sprv 2',
 'Head Park Patrol Officer',
 'Dep Dir II',
 'Assistant Inspector 2',
 'Utility Plumber Supervisor 2',
 'Electrical Trnst Mech Sprv 1',
 'Fire Rescue Paramedic',
 'IS Project Director',
 'Transit Power Line Worker',
 'Automotive Trnst Shop Sprv 1',
 'Dentist',
 'Chief Stationary Engineer',
 'Court Computer Sys Manager',
 'Manager V, MTA',
 'Sr Power Generation Tech',
 'Manager III',
 'Wire Rope Cable Maint Mechanic',
 'Sr Court Staff Attorney',
 'Transit Power Line Sprv1',
 'Utility Plumber Supervisor 1',
 'Automotive Mechanic Sprv 1',
 'Sprv Electronic Main Tech',
 'IS Engineer-Senior',
 'Nurse Midwife',
 'Manager IV, MTA',
 'Public Health Nurse',
 'Plumbing Inspector',
 'Landscape Architect',
 'Mayoral Staff XVI',
 'Court Administrator',
 'Manager,Employee Relations Div',
 'Chief Water Service Inspector',
 'Electrician Supervisor 1',
 'Director, Fiscal Services',
 'Telecommunications Tech Supv',
 'Asst Chf, Bur Clm Invest&Admin',
 'Trans and Dist Line Worker',
 'Project Manager 2',
 'Sr Light Rail Veh Equip Eng',
 'Communication Line Sprv1',
 'Sewer Repair Supervisor',
 'Manager II',
 'Airport Mechanical Maint Sprv',
 'Architectural Associate 2',
 'Transit Operator',
 'Senior Const Inspector',
 'Disability Access Coordinator',
 'Asst.Dep.Dir., Port',
 'Inspector 2',
 'Sewage Treatment Plant Supt',
 'Court Reporter Coordinator',
 'Welder',
 'Water Operations Analyst',
 'Line Inspector',
 'Senior Stationary Engineer',
 'Administrative Engineer',
 'Health Program Coordinator 3',
 'Structural Engineer',
 'Operating Room Nurse',
 'Supt Water Treatment Fac',
 'Attorney, Tax Collector',
 'Planner 5',
 'IS Business Analyst-Principal',
 'Building Plans Engineer',
 'Principal Real Property Ofc',
 'Sr. Stationary Eng, Sew Plant',
 'Automotive Mechanic',
 'Airport Electrician',
 'Utility Plumber',
 'Electrical Line Helper',
 'Stationary Engineer',
 'Power Generation Technician 2',
 'Station Agent, Muni Railway',
 'Criminalist III',
 'Director, Probate',
 'Mgr, Unified Family Court Svcs',
 'Radiologic Tech Sprv',
 'Asst Engr',
 'Airport Operations Supervisor',
 'Utility Specialist',
 'IS Engineer-Journey',
 'Senior Building Inspector',
 'Sr Statnry Eng, Wtr Treat Plnt',
 'Plumber Supervisor 1',
 'Traf Signal Electrician Sup I',
 'Manager I',
 'Director, Human Resources',
 'Claims Investigator',
 'Chief Plumbing Inspector',
 'Chief Building Inspector',
 'Airport Electrician Supervisor',
 'Stationary Eng, Sewage Plant',
 'Construction Inspector',
 'Manager III, MTA',
 'Senior Electrical Inpsector',
 'Chf Statnry Eng,WtrTreat Plnt',
 'Maintenance Controller',
 "Asst Chf Dist Atty's Invstgtor",
 'Maintenance Machinist',
 'Civil Case Settlmnt Specialist',
 'Traf Signal Electrician Sup II',
 'Operating Engineer, Universal',
 'Diagnostic Imaging Tech I',
 'Electrical Inspector',
 'Chf Stationary Eng, Sew Plant',
 'Architect',
 'Senior Personnel Analyst',
 'Assistant Law Librarian',
 'Emergency Med Svcs Agency Spec',
 'Special Nurse',
 "Med Examiner's Investigator II",
 'Electrical Line Worker',
 'Mayoral Staff XV',
 'Court Manager',
 'Communications Director',
 'IS Business Analyst-Senior',
 'Chief Electrical Inspector',
 'Lab Svcs Mgr',
 'Fire Protection Engineer',
 'Auto Body & Fender Wrk Sprv 1',
 'Utility Plumber Apprentice',
 'Ex Asst to Ex Dir, Retirement',
 'Trans Safety Specialist',
 'Protective Services Supervisor',
 'Traffic Signal Electrician',
 'Manager II, MTA',
 'Car and Auto Painter',
 'Building Inspector',
 'Survey Associate',
 'Supervising Purchaser',
 'IT Operations Support Admin II',
 'Court Reporter',
 "Med Examiner's InvestigatorIII",
 'Public SafetyComm Disp',
 'Director, Probation Services',
 'Maintenance Machinist Sprv 1',
 'Automotive Mechanic Asst Sprv',
 'Public SafetyComm Supv',
 'IS Prg Analyst-Principal',
 'Principal Personnel Analyst',
 'Sr District Atty Investigator',
 'Senior Plumbing Inspector',
 'Electrician',
 'Dep Dir I',
 'Public Relations Mgr',
 'Contract Compliance Officer 2',
 'Electr Instrmntn Tech Wtr Poll',
 'Court Staff Attorney II',
 'Senior Water Service Inspector',
 'Diagnostic Imaging Tech IV',
 'Bldg & Grounds Maint Sprv',
 'Dist Atty Investigator (SFERS)',
 'Prnpl Admin Analyst II',
 'Locksmith Supervisor 1',
 'Ct Comp App Programmer',
 'Carpenter Supervisor 2',
 'Senior Occupational Therapist',
 'Pr Administrative Analyst',
 'Sr Counselor, Juvenile Hall',
 'Transit Operations Specialist',
 'Plumber Supervisor 2',
 'Switch Repairer',
 'Safety Officer',
 'Mayoral Staff XIV',
 'Steamfitter Supervisor I',
 'Institutional Police Sergeant',
 'Project Manager 1',
 'Ex Asst to Admin, SFGH',
 'Senior Industrial Hygienist',
 'Planner 4-Environmental Review',
 'Water Conservation Admin',
 'Automotive Body & Fender Wrk',
 'Div Director, Adult Probation',
 'Govrnmt/Publ Affairs Mgr',
 'Chief Housing Inspector',
 'Plumber',
 'IT Operations Support Admin V',
 'Chief Fire Alarm Dispatcher',
 'IT Operations Support Admin IV',
 'Sr Environmental Hlth Insp',
 'Water & Power Maint Sprv 1',
 'Nursing Assistant',
 'Airport Economic Planner',
 'Electrician Supervisor 2',
 'Senior Claims Investigator',
 'Perf Analyst III Project Mgr',
 'Senior Physical Therapist',
 'Protective Services Worker',
 'Asst Forensic Toxicologist 1',
 'Supv Chemist',
 'Water Service Inspector',
 'Cable Splicer',
 'Industrial Hygienist',
 'Senior Housing Inspector',
 'Maintenance Manager',
 'Sheet Metal Supervisor 1',
 'Assistant Director, Probate',
 'Senior Property Manager, Port',
 'Chief Surveyor',
 'Mayoral Staff XIII',
 'Principal Mgmt Analyst',
 'Street Repair Supervisor 2',
 'Transit Planner 4',
 'Planner 4',
 'Real Estate Devt. Mgr, SFMTA',
 'Transit Manager 2',
 'Court Supervisor II',
 'Asst Dir of Clinical Svcs 1',
 'Senior Administrative Analyst',
 'Auditor III',
 'Supv Biologist',
 'Fiscal Services Supervisor',
 'Architectural Administrator',
 'Maintenance Planner',
 'Asphalt Finisher Supervisor 1',
 'Automotive Machinist',
 'Pr Environmental Hlth Insp',
 'Senior Emp Relations Repres',
 'Claims Adjuster',
 'Hospital Elig Wrk Supervisor',
 'Crane Mechanic Supervisor',
 'Pub Safety Communication Coord',
 'Statnry Eng Water Treat Plant',
 'Transit Power Cable Splicer',
 'Carpenter Supervisor 1',
 'Airport Communications Disp',
 'Counselor, Family Court Svc',
 'Sprv Prob Ofc, Juv Court',
 'Biologist III',
 'Automotive Machinist Sprv 1',
 'Accountant IV',
 'Track Maintenance Worker',
 'Sewer Service Worker',
 'Senior Real Property Officer',
 'Sheet Metal Wrk Supervisor 2',
 'Member, Board of Supervisors',
 'Criminalist II',
 'Elevator and Crane Technician',
 'Institutional Police Officer',
 'Media/Security Syst Supv',
 'Ct Comp Sys Engineer II',
 'Ct Comp App Analyst',
 'Municipal Stadium Groundskpr',
 'Street Environ Svcs Oprs Supv',
 'Senior Plan Checker',
 'Sprv Clincal Psychologist',
 'Heavy Equipment Ops Sprv',
 'Director, Juvenile Hall',
 'Employment & Training Spec 6',
 'EEO Senior Specialist',
 'Truck Driver',
 'Auto Machinist Asst Sprv',
 'Ex Dir, SE Com Fac Comm',
 "District Attry's Investigator",
 'Chemist III',
 'Dir, Log Cabin Ranch (SFERS)',
 'Materials Coordinator',
 'Emergency Services Coord IV',
 'IS Administrator-Supervisor',
 'Patient Care Assistant',
 'Safety Analyst',
 'Pr Real Property Appraiser',
 'Steamfitter',
 'Counselor, Juvenile Hall',
 'Transit Manager 1',
 'Principal Environ Specialist',
 'Pr Personal Property Auditor',
 'Employee Relations Representat',
 'Maritime Marketing Repr',
 'Counselor 2',
 'Housing Inspector',
 'Court Invstgtor, Superior Crt',
 'Maintenance Scheduler',
 'Coord of Citizen Involvement',
 'Asst Superintendent Rec',
 'Sheet Metal Worker',
 'Power Generation Technician 1',
 'Sr Community Dev Spec 2',
 'Sprv Wastewater Cont Inspector',
 'SrClaimsInvstgtor,Cty Atty Ofc',
 'Research Psychologist',
 'Probate Examiner',
 'Chf Victim/Witness Invstgtor',
 'Airport Safety Officer',
 'Parking Enforcement Admin',
 'Piledriver Supervisor 1',
 'Electric Motor Repairer',
 'Senior Street Inspector',
 'City Shops Asst Superintendent',
 'Counselor, Log Cabin Ranch',
 'Crime Lab Mgr',
 'Physical Therapist',
 'Occupational Therapist',
 'Airport Property Specialist 1',
 'Medical Records Tech Sprv',
 'Pipe Welder',
 'Supervising Parts Storekeeper',
 'Training Coordinator',
 'Watershed Forester',
 'Regulatory Specialist',
 'Eligibility Worker Supervisor',
 'IS Engineer-Assistant',
 "Worker's Comp Supervisor 1",
 'Licensed Vocational Nurse',
 'Environmental Health Inspector',
 'Coord, Human Rights Comm',
 'Wastewater Control Inspector',
 'Security Analyst',
 'Planner 3-Environmental Review',
 'Electric Motor Repair Sprv 1',
 'Mental Health Hearing Officer',
 'Industrial Engineer',
 'Traffic Sign Manager',
 'Street Inspection Supervisor',
 'Mech Shop & Equip Supt',
 'Court Training Specialist',
 'Cement Finisher Supervisor 1',
 'Sr Psychiatric Social Worker',
 'Benefits Supervisor',
 'Clinical Psychologist',
 'Marriage, Family & Child Cnslr',
 'Psychiatric Social Worker',
 'Planner 3',
 'Sprv Adult Probation Ofc',
 'Bd/Comm Secretary 3',
 'Asst Materials Coordinator',
 'Pile Worker',
 'Pr Payroll & Personnel Clerk',
 'Soft Floor Coverer Supvr I',
 'Emergency Services Coord III',
 'Senior Management Assistant',
 'Sup Welfare Fraud Investigator',
 'Court Interpreter Supervisor',
 'Automotive Service Worker',
 'Speech Pathologist',
 'Claims Investigator, CA',
 'Senior Microbiologist',
 'Shelter Veterinarian',
 'Senior Purchaser',
 'Arborist Technician Supervisor',
 'Sr Marriage, Fam & Cld Cnslr',
 'Deputy Probation Officer',
 'Locksmith',
 'Social Work Specialist',
 'Media/Security Sys Spec',
 'Forester',
 'IS Administrator 3',
 'IS Trainer-Senior',
 'Stage Electrician',
 'Transit Planner III',
 'Property Manager, Port',
 'Architectural Assistant 2',
 'Senior Health Educator',
 'Legislative Assistant',
 'Senior Health Program Planner',
 'Librarian 3',
 'Chf Payroll & Personnel Clerk',
 'Senior Power House Operator',
 'Park Section Supervisor',
 'Ornamental Iron Wrk Sprv 1',
 'IS Programmer Analyst-Senior',
 'Aprntc Statnry Eng, Sew Plant',
 'Heavy Equip Ops Asst Sprv',
 'Painter Supervisor 2',
 'Real Property Manager',
 'Sr Airport Communications Disp',
 'Transit Car Cleaner',
 'Gardener',
 'Senior Social Worker',
 'Pharmacy Technician',
 'Program Support Analyst',
 'Janitorial Services Supervisor',
 'Curator 4',
 'Airport Emerg Planning Coord',
 'Engineering Associate 2',
 'Asphalt Plant Supervisor 1',
 'Sr. Community Devl Spc 1',
 'Bricklayer',
 'Biologist I/II',
 'Performance Analyst II',
 'Medical Social Work Supervisor',
 'General Laborer',
 'Power House Operator',
 'Park Patrol Officer',
 'Contract Compliance Officer 1',
 'Asst Clk, Board of Supervisors',
 'Epidemiologist 2',
 'Auditor II',
 'Feasibility Analyst, Port',
 'Asst Electronic Main Tech',
 'Sr. Environmental Spec',
 'Admin Analyst 3',
 'Parking Control Officer',
 'Sr Public Defenders Invstgtor',
 'Area Sprv Parks, Squares & Fac',
 'Commercial Div Asst Sprv',
 'Carpenter',
 'Court Asst-Sr, Superior Court',
 'Landscape Architect Assoc 1',
 'Accountant III',
 'Administrative Services Mgr',
 'Senior Real Property Appraiser',
 'Fusion Welder',
 'Asst Chf Victim/Wit Invstgtor',
 'Conservatorship/Case Mgt Sprv',
 'Sr Investigator, OCC',
 'Museum Sec Supv',
 'Mayoral Staff XI',
 'Sr Personal Property Auditor',
 'Painter Supervisor 1',
 'Secretary, Comm on the Environ',
 'Employment & Training Spec 5',
 'Power Plant Supervisor 1',
 'Duty Officer',
 'Airports Communications Sprv',
 'Parking Meter Repairer Sprv 1',
 'Sprv, Traffic & Street Signs',
 'Emp & Training Spec 4',
 'Deputy Court Clerk III',
 'Eligibility Worker',
 'Food Service Mgr Administrator',
 'Patient Accounts Manager',
 'Asst Dir, Log Cabin Rnch',
 'Welfare Fraud Investigator',
 'Sr Human Resources Analyst',
 'AprntcStatnry Eng,WtrTreatPlnt',
 'IS Business Analyst',
 'Personnel/Payroll Repres',
 'General Laborer Supervisor 1',
 'Pr Investigator, Tax Collector',
 'Custodial Assistant Supervisor',
 'Librarian 2',
 'Mental Hlth Treatment Spec',
 'Mayoral Staff XII',
 'Pr Fare Collections Receiver',
 'Building Services Technician',
 'Senior Fiscal Technician',
 'Program Specialist Supervisor',
 'Arborist Technician',
 'Chemist I/II',
 'Sprv Adult Prob Ofc (SFERS)',
 'Child Support Officer III',
 'Sr Cent Proc & Dist Tech',
 'Public Relations Officer',
 'Sr General Utility Mechanic',
 'Senior Medical Social Worker',
 'Assistant Const Inspector',
 'Training Technician',
 'Admin Hearing Examiner',
 'Animal Care Supervisor',
 'Ex Asst to the Controller',
 'Secretary, Library Commission',
 'Main Machinist Asst Sprv',
 'Arborist Technician Supv II',
 'Piledriver Engine Operator',
 'Transit Fare Insp. Sup/Invst.',
 'Dental Hygienist',
 'Court Administrative Secretary',
 'Glazier',
 'Invstgtor Ofc Citizen Cmplnts',
 'Criminal Justice Specialist 2',
 'Communications Dispatcher 2',
 'Patient Accounts Supervisor',
 'Surgical Procedures Technician',
 'Senior Parking Control Officer',
 'Nutritionist',
 'Market Research Spec, Port',
 'Parts Storekeeper',
 'Personnel Analyst',
 'Program Specialist',
 'Survey Assistant II',
 'Victim/Witness Investigator 3',
 'Cement Mason',
 'Health Educator',
 'Senior Benefits Analyst',
 'Investigator,Taxi & AccessSvcs',
 'Painter',
 'Junior Engineer',
 'Cfdntal Sctry to City Atty',
 'IT Operations Support Admn III',
 'Executive Secretary 3',
 'Sr Payroll & Personnel Clerk',
 'Street Inspector',
 'Rent Board Supervisor',
 'Chief Dietitian',
 'Medical Social Worker',
 'Media Training Specialist',
 'Sr Employee Asst Counselor',
 'Microbiologist',
 'Apprentice Stationary Engineer',
 'Librarian 2 - Asian Arts',
 'Engineering Associate 1',
 'Media Production Supv',
 "Public Defender's Investigator",
 'Rehabilitation Svcs Coord',
 'Track Maint Supt, Muni Railway',
 'Cement Finisher Supervisor 2',
 'Roofer Supervisor 1',
 'Watershed Keeper',
 'IS Administrator 2',
 'Pattern Maker',
 'Sctry, Bldg Inspection Comm',
 'Clerk',
 'General Utility Mechanic',
 'Transit Planner 2',
 'Public Health Team Leader',
 'Employee Assistance Counselor',
 'Research Asst, Superior Court',
 'Chief Nursery Specialist',
 'Deputy Sheriff 1',
 'Specialist in Aging 2',
 'Watershed Keeper Supervisor',
 'Sr Fare Collections Receiver',
 'Rep, Comm Status of Women',
 'Medical Records Technician',
 'Training Officer',
 'Security Guard',
 'Transit Car Cleaner Asst Sprv',
 'Administrative Analyst',
 'Auto Svc Wrk Asst Sprv',
 'Mayoral Staff IX',
 'Dir of Act, Therapy & Vol Svcs',
 'Senior Estate Investigator',
 'Health Program Coordinator 2',
 'Social Work Supervisor',
 'Health Program Planner',
 "Worker's Compensation Adjuster",
 'Payroll Supervisor',
 'Water Quality Tech III',
 'Asst General Services Manager',
 'Water QualityTech I/II',
 'Sewer Maintenance Worker',
 'Investigator, Tax Collector',
 'Recreation Supervisor',
 'EEO Programs Specialist',
 'Physical Therapist Assistant',
 'Health Care Analyst',
 'Environmental Spec',
 'Museum Guard',
 'Court Clerk',
 'Planner 2',
 'Assistant Industrial Hygienist',
 'Senior Eligibility Worker',
 'Real Property Appraiser',
 'Med Staff Svcs Dept Anl',
 'Ornamental Iron Worker',
 'Integrated Pest Mgmt Specialst',
 'Utility Analyst',
 'Fingerprint Technician 2',
 'Librarian 1',
 'Porter Supervisor 1',
 'Community Police Services Aide',
 'Fare Collections Receiver',
 'Customer Service Agent Supv',
 'Legal Assistant',
 'Comm Pol Svcs Aide Supervisor',
 'IS Trainer-Journey',
 'Porter',
 'Architectural Assistant 1',
 'Senior Personnel Clerk',
 'Hospital Eligiblity Worker',
 'Personal Property Auditor',
 'Events & Facilities Specialist',
 'Purchaser',
 'Executive Secretary 2',
 'Secretary, Health Commission',
 'Dietitian',
 'Wharfinger 2',
 'Senior Transit Traffic Checker',
 'Prpl Permit and Citation Clerk',
 'Senior Clerk Typist',
 'Soft Floor Coverer',
 'IS Business Analyst-Assistant',
 'Emp & Training Spec 2',
 'Forensic Laboratory Technician',
 'Chief Clerk',
 'Deputy Court Clerk II',
 'Estate Investigator',
 'Volunteer/Outreach Coord',
 'ASR Senior Office Specialist',
 'Central Processing & Dist Tech',
 'Library Technical Assistant 2',
 'Employment & Training Spec 3',
 'Legal Secretary 2',
 'Assoc Musm Cnsrvt, AAM',
 'Fingerprint Technician 3',
 'Mayoral Staff X',
 'Community Development Spec',
 'Psychiatric Technician',
 'Snr Permit and Citation Clerk',
 'Fire Alarm Dispatcher',
 'Deputy Probation Officer SFERS',
 'Hodcarrier',
 'Court Paralegal',
 'Principal Water Services Clerk',
 'Assistant Storekeeper',

In [42]:
print(
    f"The number of employees with a unique title in 2013 is {len(list_unique_titles)} out of {len(list_of_all_job_titles)}."
)

The number of employees with a unique title in 2013 is 202 out of 1051.

**How many people have the word "CHIEF" in their job title? (This is a bit tricky)**

In [43]:
full_form = sal["JobTitle"].str.lower().str.contains("chief").sum()
full_form

627

In [44]:
short_form = sal["JobTitle"].str.lower().str.contains("chf").sum()
short_form

163

In [45]:
full_form + short_form

790

**Bonus: Is there a correlation between the length of the job title string and the salary?**

In [46]:
sal["title_len"] = sal["JobTitle"].apply(len)
sal["title_len"].corr(sal["TotalPayBenefits"])

-0.036878445932606675