___

<a href='https://oxiane-institut.com/'> <img src='../oxiane.jpg' /></a>\n
___

## Multiple Index and Index Hierarchy

Let's see how to work with multiple indexes. First, we'll create a quick example of what a DataFrame with multiple indexes would look like:

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside =  [   1,   2,   3,    1,  2,   3]

In [4]:
multi_index_list = list(zip(outside, inside))
multi_index_list

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [5]:
multi_index = pd.MultiIndex.from_tuples(multi_index_list)
multi_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [6]:
df = pd.DataFrame(np.random.randn(6, 2), index=multi_index, columns=["A", "B"])
df

             A         B
G1 1 -0.151646  1.698816
   2 -0.530066 -0.656376
   3 -0.078042 -0.844553
G2 1 -1.050520 -0.001320
   2  2.516274 -1.166593
   3 -0.623620 -0.913240

***Now, let's show how to index this!*** 

For the index hierarchy, we use `df.loc[]`. 

If this was on the column axis, you would simply use the normal bracket notation `df[]`. 

Calling a level of the index returns the sub-dataframe:

In [7]:
df.loc['G1']

          A         B
1 -0.151646  1.698816
2 -0.530066 -0.656376
3 -0.078042 -0.844553

In [8]:
df.loc['G1'].loc[1]

A   -0.151646
B    1.698816
Name: 1, dtype: float64

In [9]:
df.index.names

FrozenList([None, None])

In [10]:
df.index.names = ['Group','Num']

In [11]:
df

                  A         B
Group Num
G1    1   -0.151646  1.698816
      2   -0.530066 -0.656376
      3   -0.078042 -0.844553
G2    1   -1.050520 -0.001320
      2    2.516274 -1.166593
      3   -0.623620 -0.913240

### df.xs()

Return cross-section from the Series/DataFrame.

In [12]:
xs_ret = df.xs('G1')
xs_ret

            A         B
Num
1   -0.151646  1.698816
2   -0.530066 -0.656376
3   -0.078042 -0.844553

In [13]:
type(xs_ret)

pandas.core.frame.DataFrame

In [14]:
xs_ret = df.xs(('G1',1))
xs_ret

A   -0.151646
B    1.698816
Name: (G1, 1), dtype: float64

In [15]:
type(xs_ret)

pandas.core.series.Series

In [16]:
# Specify index of interest by name or by integer
df.xs(1, level='Num')

              A         B
Group
G1    -0.151646  1.698816
G2    -1.050520 -0.001320

In [17]:
df.xs(1, level=1)

              A         B
Group
G1    -0.151646  1.698816
G2    -1.050520 -0.001320